export const LOGIN = 'LOGIN';
export const AUTH_FIELD_CHANGE = 'AUTH_FILED_CHANGE'

export const SERVICE_FIELD_CHANGE = 'SERVICE_FIELD_CHANGE'
export const SERVICE_LOAD_SERVICE = 'SERVICE_LOAD_SERVICE'
export const SERVICE_ADD_NEW_PROPERTIES = 'SERVICE_ADD_NEW_PROPERTIES'
export const SERVICE_DELETE_NEW_PROPERTIES = 'SERVICE_DELETE_NEW_PROPERTIES'
export const SERVICE_PROPERTY_TITLE_CHANGED = 'SERVICE_PROPERTY_TITLE_CHANGED'
export const SERVICE_PROPERTY_CODE_CHANGED = 'SERVICE_PROPERTY_CODE_CHANGED'
export const SERVICE_CLEAR_FORMS = 'SERVICE_CLEAR_FORMS'
export const SERVICE_SELECT_SERVICE = 'SERVICE_SELECT_SERVICE'
export const SERVICE_DELETE_SERVICE = 'SERVICE_DELETE_SERVICE'
export const SERVICE_LOAD_SERVICE_INFO = 'SERVICE_LOAD_SERVICE_INFO'

export const DEVICE_FIELD_CHANGE = 'DEVICE_FIELD_CHANGE'
export const DEVICE_LOAD_DEVICES = 'DEVICE_LOAD_DEVICES'
export const DEVICE_SELECT_DEVICE = 'DEVICE_SELECT_DEVICE'
export const DEVICE_ON_SELECT_SERVICE = 'DEVICE_ON_SELECT_SERVICE'
export const DEVICE_CLEAR_FORMS = 'DEVICE_CLEAR_FORMS'
export const DEVICE_LOAD_DEVICE_INFO = 'DEVICE_LOAD_DEVICE_INFO'


