export const LOGIN = 'LOGIN';
export const AUTH_FIELD_CHANGE = 'AUTH_FILED_CHANGE'

export const SERVICE_FIELD_CHANGE = 'SERVICE_FIELD_CHANGE'
export const SERVICE_LOAD_SERVICE = 'SERVICE_LOAD_SERVICE'