export const LOGIN = 'LOGIN';
export const AUTH_FIELD_CHANGE = 'AUTH_FILED_CHANGE'

export const SERVICE_FIELD_CHANGE = 'SERVICE_FIELD_CHANGE'
export const SERVICE_LOAD_SERVICE = 'SERVICE_LOAD_SERVICE'
export const SERVICE_ADD_NEW_PROPERTIES = 'SERVICE_ADD_NEW_PROPERTIES'
export const SERVICE_DELETE_NEW_PROPERTIES = 'SERVICE_DELETE_NEW_PROPERTIES'
export const SERVICE_PROPERTY_TITLE_CHANGED = 'SERVICE_PROPERTY_TITLE_CHANGED'
export const SERVICE_PROPERTY_CODE_CHANGED = 'SERVICE_PROPERTY_CODE_CHANGED'